steps:

## multiline script
- name: golang:1.20.3
  entrypoint: /bin/bash
  args: 
    - -c
    - |
      pwd; GO_ENABLED=0 GOOS=linux go build webserver.go 

## build the image of webserver and push it in the same runtime image docker in docker to google container registry gcr.io 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gowebserver-1/webserver', '.']
images: ['gcr.io/gowebserver-1/webserver']

