timeout: 1200s
substitutions:
  _CUSTOM_REGION: us-central1
  _CUSTOM_CLUSTER: gitlab-terraform-gke 

steps:

## multiline script
- name: golang:1.20.3
  entrypoint: /bin/bash
  args: 
    - -c
    - |
      pwd; GO_ENABLED=0 GOOS=linux go build webserver.go 

## build the image of webserver and push it in the same runtime image docker in docker to google container registry gcr.io 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gowebserver-1/webserver', '.']


## Prepare kubeconfig
- name: 'gcr.io/cloud-builders/kubectl'
  id: Configure kubectl
  args:
    - cluster-info
  env:
    - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
    - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
    - KUBECONFIG=/workspace/.kube/config

## deploy with helm
- name: 'gcr.io/gowebserver-1/helm'
  id: Deploy chart
  args:
    - upgrade
    - -i
    - webserver
    - ./webserverchart
    - -f
    - ./webserverchart/values.yaml
  env:
    - KUBECONFIG=/workspace/.kube/config
    - TILLERLESS=true

images: ['gcr.io/gowebserver-1/webserver']
