steps:

## multiline script
- name: 'gcr.io/cloud-builders/go'
  entrypoint: '/bin/bash'
  args:
  - '-eEuo'
  - 'pipefail'
  - '-c'
  - |- 
    GO_ENABLED=0 GOOS=linux go build webserver.go

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gowebserver/webserver', '.']
images: ['gcr.io/gowebserver/webserver']

